sudo: false

language: node_js

node_js: 
  - node
  
cache: npm

before_script:
  - npm ci

script:
  - npm test

after_script:
  - npm run coverage
  - npm run coverage_report

notifications:
  - email: false